name: Windows CI for HwCodecDetect

on:
  push:
    branches: [ main, testci ]
  pull_request:
    branches: [ main, testci ]

jobs:
  test-on-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Clone HwCodecDetect
      run: git clone https://github.com/whyb/HwCodecDetect.git

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      working-directory: HwCodecDetect

    - name: Install dependencies
      run: python -m pip install -r requirements.txt
      working-directory: HwCodecDetect

    - name: Run tests
      run: python -m src.HwCodecDetect.run_tests
      working-directory: HwCodecDetect
