name: Run CI

on:
  push:
    branches: [ main, testci ]
  pull_request:
    branches: [ main, testci ]

jobs:
  test-on-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    env:
      PYTHONIOENCODING: utf-8

    steps:
    - name: Clone HwCodecDetect
      run: git clone -b main --single-branch https://github.com/whyb/HwCodecDetect.git

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      working-directory: HwCodecDetect

    - name: Install dependencies
      run: python -m pip install -r requirements.txt
      working-directory: HwCodecDetect

    - name: Run tests
      run: python -m src.HwCodecDetect.run_tests
      working-directory: HwCodecDetect

  test-on-ubuntu:
    runs-on: ubuntu-latest

    env:
      PYTHONIOENCODING: utf-8

    steps:
    - name: Install Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Clone HwCodecDetect
      run: git clone -b main --single-branch https://github.com/whyb/HwCodecDetect.git

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y snapd
        sudo snap install ffmpeg
        ffmpeg -version

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      working-directory: HwCodecDetect

    - name: Install dependencies
      run: python -m pip install -r requirements.txt
      working-directory: HwCodecDetect

    - name: Run tests
      run: python -m src.HwCodecDetect.run_tests
      working-directory: HwCodecDetect

  test-on-macos:
    runs-on: macos-latest

    env:
      PYTHONIOENCODING: utf-8

    steps:
    - name: Install Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Clone HwCodecDetect
      run: git clone -b main --single-branch https://github.com/whyb/HwCodecDetect.git

    - name: Install FFmpeg
      run: |
        brew update
        brew install ffmpeg
        ffmpeg -version

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      working-directory: HwCodecDetect

    - name: Install dependencies
      run: python -m pip install -r requirements.txt
      working-directory: HwCodecDetect

    - name: Run tests
      run: python -m src.HwCodecDetect.run_tests
      working-directory: HwCodecDetect
